version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "node_modules/**",
  "var/**",
  "vendor/**",
  "assets/vendor/**",
  "migrations/**",
  "tests/**"
]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "php"

[[transformers]]
name = "php-cs-fixer"